### ISSUE TITLE
Icons coloring within Buttons and TextFields

### ISSUE THREAD

**Issue by andrew-codes** [versionone/component-library#41]
Icon colors should be overridden via the **theme** when placed in Button (of varying types) and TextFields (as password fields or as prefix/appended items).

**Comment by kmmarsh** [comment]
Now accepts Color: https://github.com/versionone/component-library/blob/master/packages/icons/src/utils/Base.js#L20

Which can be passed from theme: https://github.com/versionone/component-library/blob/master/packages/components/src/Button/IconButton.js#L143
