### ISSUE TITLE
Switch doesn't behave as expected when passing default state

### ISSUE THREAD

**Issue by CWSites** [versionone/component-library#81]
While working within CTM @mickeyrogers and I observed some unexpected behavior. The switch itself worked fine unless we passed state to it for the `checked` prop. After spending a couple hours on it we tried a regular checkbox and it worked fine.

**Comment by walkerrandolphsmith** [comment]
Can you express what the expected behavior was? If you pass a checked prop then the switch should reflect exactly that state independent of further user interaction. Controlled vs. uncontrolled React components. Can you verify this is still an issue?

**Comment by CWSites** [comment]
Can you clarify "switch should reflect exactly that state independent of further user interaction"?

**Expected behavior:** When I pass a default value of `true` to the checked prop then the switch should show that it's checked. When the user clicks the switch to turn it off then the switch should show that it's unchecked.

**Comment by kmmarsh** [comment]
Talked with Matt, the source of his issue was not the switch. Closing
